buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.4.1'
    }
}

ext {
    coreKtxVersion = '1.13.1' // Update to latest stable if available
    appCompatVersion = '1.7.0' // Update to latest stable if available
    materialVersion = '1.12.0' // Update to latest stable if available
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
